# Generated by Django 5.2.6 on 2025-09-30 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(blank=True, max_length=50, null=True)),
                ('receita', models.TextField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
                ('mestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ('nome_prato', 'mestre'),
            },
        ),
    ]
