# Generated by Django 5.2.6 on 2025-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tempo de preparo'),
        ),
    ]
