# Generated by Django 5.2.7 on 2025-10-13 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0002_receita_ativa_receita_popular_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ('nome_prato', 'categoria', 'mestre'), 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('D', 'Doce'), ('S', 'Salgada')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_prato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do prato'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tempo de preparo (em minutos)'),
        ),
    ]
